version: 2
jobs:
  release:
    docker:
        - image: circleci/ruby:2.6.2
    steps:
      - checkout:
      - restore_cache:
          keys:
            - gem-cache-v2-{{ checksum "Gemfile.lock" }}
            - gem-cache-v2-
      - run:
          name: "Bundle install"
          command: "bundle install --path vendor/bundle"
      - save_cache:
          key: gem-cache-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - "vendor/bundle"
      - run:
          name: "Release public sdk"
          command: "bundle exec rake release"
      - persist_to_workspace:
          root: "~/project"
          paths: 
          - "*"

workflows:
  version: 2
  release_flow:
    jobs:
      - approve_release:
          type: approval
      - release:
          requires:
          - approve_release




